name = "SPIRV"
uuid = "84138a67-b342-4d33-8200-33cfcca52eb2"
authors = ["CÃ©dric Belmant"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
SPIRV_Headers_jll = "50296a37-19d4-5487-a1d5-621c23d0d175"

[compat]
CEnum = "0.4.1"
Crayons = "4.0"
MLStyle = "0.4"
SPIRV_Headers_jll = "1.5"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
