name = "SPIRV"
uuid = "84138a67-b342-4d33-8200-33cfcca52eb2"
authors = ["CÃ©dric Belmant"]
version = "0.2.3"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
CodeInfoTools = "bc773b8a-8374-437a-b9f2-0e9785855863"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ResultTypes = "08a2b407-ddc3-586a-afd6-c784ad1fffe2"
SPIRV_Tools_jll = "6ac6d60f-d740-5983-97d7-a4482c0689f4"
SwapStreams = "0b152c4a-7e29-418b-9258-223db38db9d9"

[compat]
AbstractTrees = "0.4"
Accessors = "0.1"
AutoHashEquals = "0.2"
CEnum = "0.4.1"
CodeInfoTools = "0.3"
Dictionaries = "0.3"
Graphs = "1"
MLStyle = "^0.4.11"
Reexport = "1"
ResultTypes = "3"
SwapStreams = "0.2"
julia = "1.7"

[extras]
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "MetaGraphs"]
